Hc9 add common components
BinaryStudioAcademy/bsa-winter-2021-healthcare pull request #13
Opened 2021-03-10 16:39 UTC by dnzln

2021-03-10 17:01 UTC, ZubkoWhatislove requested changes
Very good 👍
Make the `isDisabled` prop is optional for all

2021-03-10 17:01 UTC, ghost commented on frontend/package.json
> +    "@types/react-datepicker": "3.1.7",
Should be in the dev dependencies
(reinstall it properly)

2021-03-10 17:01 UTC, ghost commented on frontend/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;700&display=swap" rel="stylesheet">
```suggestion
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">

```

2021-03-10 17:01 UTC, ghost commented on frontend/src/common/enums/app/button.enum.ts
> +enum ButtonStyleType {
Move enums to frontend/src/common/enums/form/button.enum.ts

And move each enum into separate file

2021-03-10 17:01 UTC, ghost commented on frontend/src/common/enums/app/button.enum.ts
> +  WITH_BORDER = 'bordered',
In such enums key and value should be the same (it's for all enums connected with styles)

2021-03-10 17:01 UTC, ghost commented on frontend/src/common/enums/app/input.enum.ts
> +enum InputType {
Move enums to frontend/src/common/enums/form/button.enum.ts

And move each enum into separate file

2021-03-10 17:01 UTC, ghost commented on frontend/src/common/types/form/select.type.ts
> +type SelectChangeCallback = (evt: SelectChangeEvent) => void;
move each type to a separate file

2021-03-10 17:01 UTC, ghost commented on frontend/src/components/common/button/button.tsx
> +const Button: React.FC<Props> = ({ type, styleType, color, label, isDisabled, hasHiddenLabel, icon, onClick }) => (
```suggestion
const Button: React.FC<Props> = ({ type = ButtonType.BUTTON, styleType, color, label, isDisabled, hasHiddenLabel, icon, onClick }) => (
```

2021-03-10 17:01 UTC, ghost commented on frontend/src/components/common/checkbox/checkbox.tsx
> +  </p>
```suggestion
  <label className={clsx(styles.checkboxRow, hasError && styles.error)}>
    <input
      onChange={onChange}
      checked={isChecked}
      disabled={isDisabled}
      name={name}
      className={styles.checkboxInput}
      type="checkbox"
    />
   <span className={styles.checkboxLabel}>
      {label}
   </span>
  </label>
```

2021-03-10 17:01 UTC, ghost commented on frontend/src/components/common/date-input/date-input.tsx
> +const DateInput: React.FC<Props> = ({ onChange, isDisabled, isError, selectedDate }) => (
```suggestion
  hasError: boolean;
}

const DateInput: React.FC<Props> = ({ onChange, isDisabled, hasError, selectedDate }) => (
```
make it consistent

2021-03-10 17:01 UTC, ghost commented on frontend/src/components/common/radio/radio.tsx
> +);
We need to render in as an array. So you need to pass array of options(IOption[])

2021-03-10 17:01 UTC, ghost commented on frontend/src/components/common/select/select.tsx
> +}
Move it to the common/interfaces/form to reuse it for `Radio`  component

2021-03-10 17:01 UTC, ZubkoWhatislove commented on frontend/src/components/common/select/select.tsx
> +        </option>;
```suggestion
  <select className={clsx(styles.select, hasError && styles.error)} onChange={onChange} disabled={isDisabled}>
    {
      options.map(option => {
        return <option
          key={option.value}
          value={option.value}
        >
          {option.label}
        </option>;
```

2021-03-10 20:10 UTC, ghost requested changes

2021-03-10 20:10 UTC, ghost commented on frontend/src/components/common/button/button.tsx
> +    {hasHiddenLabel ? <span className={styles.visuallyHidden}>{label}</span> : label}
```suggestion
    {hasHiddenLabel ? <span className="visually-hidden">{label}</span> : label}
```
Move this class to the global styles(index.scss)

2021-03-10 20:10 UTC, ZubkoWhatislove commented on frontend/src/components/common/radio/radio.tsx
> +            />
```suggestion
interface Props {
  options: IOption<string>[];
  value: string;
  isDisabled?: boolean;
  hasError?: boolean;
  name: string;
  onChange: InputChangeCallback;
}

const Radio: React.FC<Props> = ({ options, value, isDisabled, hasError, name, onChange }) => (
  <div className={styles.radioContainer}>
    {
      options.map(option => (
          <label
            key={option.value}
            className={clsx(styles.radioLabel,
              hasError && styles.error,
              isChecked && styles.isChecked)
            }
          >
            {option.label}
            <input
              onChange={onChange}
              checked={option.value === value}
              disabled={isDisabled}
              name={name}
              value={option.value}
              className={styles.radioInput}
              type="radio"
            />
```

2021-03-10 20:10 UTC, ZubkoWhatislove commented on frontend/src/components/common/select/select.tsx
> +  <select className={clsx(styles.select, hasError && styles.error)} onChange={onChange} disabled={isDisabled}>
Add `label` tag for select and `label` as prop

2021-03-10 20:10 UTC, ZubkoWhatislove commented on frontend/src/components/common/text-input/text-input.tsx
> +    <p className={styles.labelText}>{label}</p>
```suggestion
    <span className={styles.labelText}>{label}</span>
```
label is a string tag. It can't contain any block elements

2021-03-11 06:29 UTC, ZubkoWhatislove approved these changes
👍

2021-03-11 06:30 UTC, merged

2021-03-11 18:17 UTC, Yarikks commented on frontend/src/common/enums/form/botton-color.enum.ts
> +enum ButtonColor {
botton-color.enum.ts -> button-color.enum.ts
And same for the botton-style & botton-icon