Hc21 doctor's details component
BinaryStudioAcademy/bsa-winter-2021-healthcare pull request #17
Opened 2021-03-12 06:39 UTC by ReznikYuriy

2021-03-12 17:16 UTC, What1s1ove requested changes

2021-03-12 17:16 UTC, What1s1ove commented on frontend/src/app.tsx
> +    <Route path="/details" component={DoctorDetails} />
Use AppRoute

2021-03-12 17:16 UTC, What1s1ove commented on frontend/src/components/doctor-details/doctor-details.tsx
> +const doctor = {
Now you need to remove mocks and fetch a real user

2021-03-16 17:01 UTC, ZubkoWhatislove requested changes
Good 👍

2021-03-16 17:01 UTC, ghost commented on frontend/src/components/doctor-details/doctor-details.tsx
> +  const { pathname } = useLocation();
```suggestion
  const { id: userId } = useParams();
```

2021-03-16 17:01 UTC, ghost commented on frontend/src/components/doctor-details/doctor-details.tsx
> +      {dataStatus === DataStatus.SUCCESS &&
```suggestion
  }, [])
  
  
  if (dataStatus === DataStatus.PENDING) {
    return <div>...Loading</div>;
  }

  return (
    <div className={styles.doctorsDetailsContainer}>
```

2021-03-16 17:01 UTC, ghost commented on frontend/src/components/doctor-details/doctor-details.tsx
> +import { useEffect } from 'react';
```suggestion
```

2021-03-16 17:01 UTC, ghost commented on frontend/src/components/doctor-details/doctor-details.tsx
> +import { useLocation } from 'react-router-dom';
Packages should be before source code

2021-03-16 17:01 UTC, ghost commented on frontend/src/components/doctor-details/doctor-details.tsx
> +  useEffect(() => {
```suggestion
  React.useEffect(() => {
```

2021-03-16 17:01 UTC, ghost commented on frontend/src/components/doctor-details/doctor-details.tsx
> +                <img src={phoneIcon} alt="phone-icon" />
always add width, height, loading attr for image

2021-03-16 17:01 UTC, ghost commented on frontend/src/components/doctor-details/styles.module.scss
> +    // height: 89px;
```suggestion
```

2021-03-16 17:01 UTC, ghost commented on frontend/src/store/slices/doctors/doctors.slice.ts
> +} from 'healthcare-shared/common/enums';
```suggestion
} from 'common/enums';
```

2021-03-16 17:01 UTC, ghost commented on frontend/src/store/slices/doctors/doctors.slice.ts
> +  doctorDetails: IDoctorDetails;
```suggestion
  doctorDetails: IDoctorDetails | null;
```

2021-03-16 17:01 UTC, ghost commented on frontend/src/store/slices/doctors/doctors.slice.ts
> +  },
```suggestion
  doctorDetails: null,
```

2021-03-16 17:01 UTC, ghost commented on shared/src/common/interfaces/doctor-details/doctor-details.instance.ts
> +}
I think that we already have doctor interface

2021-03-16 17:01 UTC, ZubkoWhatislove commented on backend/src/api/user/user.api.ts
> +      (doctorDetails?.type === UserType.DOCTOR ) ? res.status(HttpCode.OK).json(doctorDetails) : res.status(HttpCode.BAD_REQUEST).json('Error! This user is not a doctor!');
```suggestion
      const doctorDetails = await userService.getDoctorDetailsById(req.params.id);
      const isDoctorType = checkIsOneOf(doctorDetails.type, UserType.DOCTOR);
      
      if (!isDoctorType) {
        return res.status(HttpCode.BAD_REQUEST).json(['Error! This user is not a doctor!']);
      }
      
      return res.status(HttpCode.OK).json(doctorDetails);
```

2021-03-17 10:19 UTC, ZubkoWhatislove requested changes
👍

2021-03-17 10:19 UTC, ZubkoWhatislove commented on frontend/src/app.tsx
> +    <Route path="/details/:id" component={DoctorDetails} />
```suggestion
    <Route path="/details/:id" component={DoctorDetails} />
```
Use AppRoute enum here

2021-03-17 10:19 UTC, ZubkoWhatislove commented on frontend/src/components/doctor-details/doctor-details.tsx
> +}
Move it to `frontend/src/components/doctor-details/common/interfaces`

2021-03-17 10:19 UTC, ZubkoWhatislove commented on frontend/src/components/doctor-details/doctor-details.tsx
> +        <img className={styles.doctorImage} src={doctorDetails?.imagePath} width="58" height="60" loading="lazy"
```suggestion
        <img className={styles.doctorImage} src={doctorDetails.imagePath} width="58" height="60" loading="lazy"
```
Remove all optional chaining

2021-03-17 10:19 UTC, ZubkoWhatislove commented on frontend/src/components/doctor-details/styles.module.scss
> +  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
```suggestion
```

2021-03-17 10:19 UTC, ZubkoWhatislove commented on frontend/src/services/user-api/user-api.service.ts
> +    return this.#http.load(`${this.#apiPrefix}${ApiPath.USERS}/details/${id}`, {
```suggestion
    return this.#http.load(`${this.#apiPrefix}${ApiPath.USERS}/${UsersApiPath.DOCTOR_DETAILS}/${id}`, {
```

2021-03-17 10:19 UTC, ZubkoWhatislove commented on shared/src/common/enums/api/users-api-path.enum.ts
> +  DETAILS_$ID = '/details/:id',
```suggestion
  DOCTOR_DETAILS_$ID = '/doctor-details/:id',
```

2021-03-17 12:45 UTC, ZubkoWhatislove approved these changes
LGTM 👍

2021-03-17 12:45 UTC, merged